#Name list for producing combined name. Add anything! 

def get_realistic_names_pool():
    return [
        "Amy", "Ada", "Ann", "Bob", "Ben", "Dan", "Don", "Eli", "Eva", "Ian", 
        "Jan", "Jon", "Jay", "Joy", "Leo", "Liz", "Max", "Mae", "Ned", "Ray", 
        "Roy", "Sam", "Tom", "Tim", "Van", "Zac", "Zoe",
        "Anna", "Abby", "Alan", "Alex", "Alma", "Amos", "Andy", "Beth", "Bill", 
        "Brad", "Carl", "Cody", "Cole", "Dale", "Dave", "Dean", "Dora", "Earl", 
        "Eden", "Eric", "Evan", "Emma", "Faye", "Fred", "Gary", "Greg", "Gwen", 
        "Hank", "Hugo", "Iris", "Jack", "Jake", "Jane", "Jean", "Jeff", "Jill", 
        "Joan", "John", "Jose", "Judy", "Karl", "Kate", "Kirk", "Kyle", "Lana", 
        "Lane", "Lara", "Leo", "Leon", "Levi", "Liam", "Lily", "Lisa", "Lois", 
        "Lora", "Luke", "Lucy", "Marc", "Mark", "Mary", "Matt", "Max", "Maya", 
        "Milo", "Mona", "Myra", "Nate", "Neal", "Ned", "Noah", "Nora", "Omar", 
        "Owen", "Paul", "Pete", "Ray", "Reed", "Rick", "Rob", "Rosa", "Rose", 
        "Ross", "Ruby", "Ruth", "Ryan", "Sara", "Sean", "Seth", "Tony", "Todd", 
        "Troy", "Tina", "Toby", "Vera", "Wade", "Walt", "Will", "Zack", "Zane",
        "Aaron", "Alvin", "Amber", "Andre", "Angel", "Anita", "April", "Arlene", 
        "Barry", "Benny", "Betty", "Blake", "Bobby", "Brady", "Brian", "Bruce", 
        "Bryan", "Caleb", "Carol", "Casey", "Cesar", "Chloe", "Chris", "Clara", 
        "Clark", "Craig", "Danny", "David", "Derek", "Devin", "Diana", "Diego", 
        "Donny", "Doris", "Drake", "Dylan", "Edgar", "Edith", "Elena", "Elias", 
        "Elsie", "Emily", "Erica", "Ethan", "Evelyn", "Faith", "Felix", "Fiona", 
        "Frank", "Freddie", "Gavin", "Gemma", "George", "Grace", "Grant", "Harry", 
        "Hazel", "Henry", "Holly", "Homer", "Isaac", "Isabel", "Jacob", "Jaime", 
        "James", "Jamie", "Janet", "Jason", "Jayne", "Jerry", "Jesse", "Jesus", 
        "Jimmy", "Jonah", "Jorge", "Josie", "Juan", "Judith", "Julia", "Julie", 
        "Justin", "Karen", "Kasey", "Keith", "Kelly", "Kevin", "Laura", "Larry", 
        "Leah", "Lewis", "Linda", "Logan", "Louis", "Lucas", "Lucia", "Lydia", 
        "Mable", "Marco", "Marie", "Mario", "Marsha", "Marty", "Megan", "Miles", 
        "Molly", "Myrtle", "Nancy", "Naomi", "Nadia", "Nolan", "Oliver", "Oscar", 
        "Owen", "Paige", "Paula", "Peter", "Philip", "Rachel", "Ralph", "Randy", 
        "Ray", "Renee", "Rhonda", "Ricky", "Riley", "Robert", "Robin", "Roger", 
        "Roman", "Ronnie", "Rowan", "Rufus", "Sally", "Sammy", "Sarah", "Scott", 
        "Shane", "Shaun", "Shawn", "Sheila", "Simon", "Sofia", "Stacy", "Steve", 
        "Susan", "Sylvia", "Tammy", "Teddy", "Terry", "Tessa", "Thomas", "Timmy", 
        "Tommy", "Tracey", "Travis", "Tyler", "Valerie", "Vance", "Vicky", "Victor", 
        "Vince", "Wanda", "Wayne", "Wendy", "Wesley", "Wyatt", "Xavier", "Zachary",
        "Albert", "Alfred", "Amanda", "Angela", "Andrew", "Andrea", "Arthur", 
        "Ashley", "Austin", "Barbra", "Brooke", "Brenda", "Carter", "Calvin", 
        "Charles", "Cheryl", "Claude", "Connor", "Daniel", "Daphne", "Dennis", 
        "Donald", "Dorothy", "Duncan", "Edward", "Eileen", "Elaine", "Elijah", 
        "Evelyn", "Frances", "George", "Gerald", "Gladys", "Gloria", "Gordon", 
        "Graham", "Gregory", "Harold", "Harvey", "Hector", "Howard", "Hunter", 
        "Ingrid", "Jackie", "Jaguar", "Janice", "Jasper", "Jeffrey", "Jeremy", 
        "Jerome", "Jessie", "Jordan", "Joseph", "Joshua", "Judith", "Julian", 
        "Justin", "Marcus", "Martin", "Marvin", "Mathew", "Melvin", "Monica", 
        "Nathan", "Nelson", "Oliver", "Olivia", "Pamela", "Parker", "Patrick", 
        "Philip", "Rachel", "Regina", "Robert", "Ronald", "Samuel", "Sandra", 
        "Sharon", "Sheila", "Sidney", "Sophia", "Steven", "Sylvia", "Taylor", 
        "Teresa", "Thomas", "Timothy", "Travis", "Victor", "Walter", "Wesley", 
        "William",
        "Abigail", "Abraham", "Anthony", "Barbara", "Beatrice", "Benjamin", 
        "Bradley", "Brandon", "Brendan", "Charles", "Charlie", "Clayton", 
        "Clifford", "Cynthia", "Deborah", "Douglas", "Eleanor", "Gilbert", 
        "Gregory", "Herbert", "Jackson", "Jeffrey", "Leonard", "Malcolm", 
        "Matthew", "Michael", "Natalie", "Patrick", "Phillip", "Raymond", 
        "Rebecca", "Richard", "Russell", "Stephen", "Timothy", "Vincent", 
        "Zachary", "Canyon", "Kyra", "Aini", "Adela", "Allie"
    ]
